### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Miklet** [kentcdodds/write-fewer-longer-tests-demo#1]
Hi Kent! I totally agree with your approach and I use it when writing my components, but what if beside success and failure scenario there are more ways to render my component. Let's imagine a component which fetches some data about some product and all it does it displays information about that product as key value pairs.
```
// first it loads data and display appropriate information about it's current state
loading...

// after it finished loading, displays informations
key1 value1
key2 value2
key3 value3
key4 value4
```

The test for this scenario is simple. Wait till loader dissappears and then verify if correct values are displayed. What if one of my values can be in different state, ex. value for `key3` can be `true` or `false`.
```
key1 value1
key2 value2
key3 value3 ? 'value is true' : 'value is false'
key4 value4
```

Currently I would write two tests, one rendering with some default payload (`value3` equals `true`) and second verifying if correct text is displayed depending on value of `value3`. Right now, I could change my code to something like this:
```
key1 value1
value3 && (key2 value2)
key3 value3 ? 'value is true' : 'value is false'
key4 value4
```

None of my tests would fail but my code wouldn't work correctly.

Shall I verify every key value pair again in each test? I struggle with this situation and wanted to ask you about advice 😫

**Comment by kentcdodds** [comment]
Basically I like to do higher-level tests for happy-path stuff, and then I do more fine grained tests for edge cases. Hopefully that helps!
